apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-my-app-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        env: staging
    spec:
      containers:
        - name: my-app
          image: holuphilix/my-k8s-app:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: API_KEY
