apiVersion: v1
data:
  API_KEY: eW91cl9wcm9kX2tleQ==
kind: Secret
metadata:
  creationTimestamp: "2025-09-04T21:19:12Z"
  name: my-app-my-app-secret-prod
  namespace: default
  resourceVersion: "78096"
  uid: a45da78a-2e0f-4401-92bc-7a1280406b96
type: Opaque
