apiVersion: v1
data:
  API_KEY: eW91cl9zdGFnaW5nX2tleQ==
kind: Secret
metadata:
  creationTimestamp: "2025-09-04T21:19:11Z"
  name: my-app-my-app-secret-staging
  namespace: default
  resourceVersion: "78094"
  uid: cd4db5ca-dfdd-48a5-924a-79afd31337ea
type: Opaque
