# helm-charts/my-app/values.yaml

replicaCount: 1

image:
  repository: holuphilix/my-k8s-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: my-app.local
      paths:
        - /
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Add serviceAccount defaults to fix nil pointer errors
serviceAccount:
  create: true
  name: ""

# Optional overrides
nameOverride: ""
fullnameOverride: ""
