# helm-charts/my-app/values.yaml

replicaCount: 2

image:
  repository: holuphilix/my-k8s-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# Add this section to fix ingress errors
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: my-app.local
      paths:
        - /
  tls: []
