---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-app-my-app-secret-staging
  namespace: default
spec:
  encryptedData:
    API_KEY: AgBBjqioLy3ET36921tcHWmnRKu/4UKB2N6/aLCqB1+QktSK9SzfIcjRdO6D1y+GsMJ8nL9UtbJUiorJvtpZHrHiy+tdSU4WGfUZ7bjoj3Q/9BhUFTGEWbPnFrmfABGI8WlYpTIm1W8Y8XZb+0V1TsjeOEhuJJ4YXiqq/pIXesPXMFxTzpLisKnEBsAc9NKc6XSpPg/D5w2e8gAwpNingF+Ax6+nU+UhBGEdgskLD5QdfDAKirctaj2ugadp71XR/g3xVwbOEaC+D3flFsxN4xrrdRZqNvci5PnWANYWDRNaS9/hnmlERG0KTA6El1X3UhRrPYc5CLXO/zMN5EgpXXfSWwlI6Ko6lKZb8LhGFGZ+4Cq3rUzcm6eLx89UMDN3p3oEhYduytX2s8ZI3hVE1D7b2mpR+BtnGe/G2GhqZuy/Q80EpIq9HsH7shY+jyRPb54avQ6zsg9qH6rzYUtXuDRqftxW1BJ19Tt7lkJ5rwnnmmjZ5HKOiKUhzbjnvSY9JOJN92GvEx/zcXXJ1Md+h3CNLxoILu8uCJa9zXdfdMX4dokrKJYC/V/TJMO10yMOVCtQXmE2FS0kyzxeJGZ0KERFNgaBUDd09/Tiq/qi1jewyUvwrsosCmCa4I992VkjHINXmm7aUI9lwVwf+tGEMCW0CPx5OuL7oPJBSLVRqYeHfwbD3yKg16f2FRd/S/1mtqPQIpUdEBtY8FTS
  template:
    metadata:
      creationTimestamp: null
      name: my-app-my-app-secret-staging
      namespace: default
