---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-app-my-app-secret-dev
  namespace: default
spec:
  encryptedData:
    API_KEY: AgBlRviN0cS+qOMO8dLWAGkSftLwck+mw+2PKjUaUugQVw2QKk8ZsP0Uc0bU3IVoCuhL7fsx3oeueiQddhoYxmKNcgE8v+kg7iJsLjwXJxbXLgkamr2R1UUHRMdf3gsrvbXc5PzF8d2OpOhHRn9C91ALfCDOOQP1cunNBIX36r7VNW90JPuVLVHccLtpvS2d2u5N8wv5T0Wzx4w07rOosUuwW0ewX1/tcG0blYUk4OklY7icLh2Kb5c2mfVrEv1O0CmE87tm7bO/VBefX4umilqmyDTLRwoQQQ07LWiJvkfQPg74L5kyld/mobTL7sReRFJKF6mtz/fCeDvDEycA6huQWcN1rDwQyeF01HSEfccqUiTsLp71EOlqfjoG64bfouJo8sTDcsxaH5HLQ6hse9ybfA9nSgqmpoQdBmEDWcWoMOM4WYZ0Nq3gNuwLm2z+USNcDy03nJFMavRqF6qiLFLLlE+yg06zPjLcdfR8VafA/km4xFF397/Ip3PHi5ccaDqCrtfogu6wMSVeaGPwEYt2jUe6wxY3COAsBqgfJsxmF2MxcGBBxF7rE1PJoD39g0W+PDFmbf96dhwLsMYaFjfXR7+N42hcWIYCAUkImzPrq1vjuVxI1HG6Z9sVVzROpXBHMPx/xuogz6Zr/7WN2DNBWPRC97z2jMMfkn25VtTqH7suYpULYQP6UYd3n3vSilMsGu1HgIoxu14NlFIhe4M=
  template:
    metadata:
      creationTimestamp: null
      name: my-app-my-app-secret-dev
      namespace: default
    type: Opaque
