apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-app-secret
  namespace: default
spec:
  encryptedData:
    API_KEY: AgAn4xcirAN8xDRHl0tOJchFOTttYV0DZ9XYmcEMBql6V1x+tSb24JwEHuy2HRte2boULijjBTn74k2A7fw7XWyPs1zOc2uBVdVkc/t2PvNBxZQoiuKFNTltswcHaknSgh19TZdmX51tFKNoarCOBjHKydEwZdqkHEcJ/IqoJnagA/YNQC46KiAY0g/5IxRH8mNnlpgGvXu64UAv+IzFg6TZXjdNPPkVw/d67L/7mPZ5oHqC9UWylyD6GTrMqEk8Mb4g4vRG3uxyfvKEeuNzXaLj2QIX/9V1PUaK3wyweXeat1riMZsy8h9Sv4YZytGwh1tXRUTXIoyN3E7oWS3hw8j/ED2A39aVdWpgn7PFYjrvAhoJQIzkkHRDIC5N68bR0D0RvyPe0niAwphUz0RsdfuZK8NG3dD2C29S5vPQfCxhrljYV1ZIvqqjwr38zeNK0UpifoFpZ+tXZH8Gy3/DyLRyT8YLOMRE1UEX1vgfTlnnmINEpSHMFoJgfd2p3921f5zUrslvux8n3Jv0szsG1ejqqVk9cE67ulfQXQwf27OI1lcK+/Z63Jt//nokqAmCf1X+jbujmnN+D5z347HUmew3KSGavYU6QDuXI1d7pO9y7oCwmLGSDP31JJuPxILYgHIK8VI5hiNgWLSEROqYvga2F/CzD+E8JCU7O+dlF09Pz7ACHvHYxslMxizN4SfaT63FwYfhtYyELF8rGF8o0dM=
  template:
    metadata:
      creationTimestamp: null
      name: my-app-secret
      namespace: default
